name: Deploy to Azure WebApp

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure Container Registry (ACR)
        run: |
          echo ${{ secrets.AZURE_ACR_PASSWORD }} | docker login ${{ secrets.AZURE_ACR_SERVER }} -u ${{ secrets.AZURE_ACR_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build . -t ${{ secrets.AZURE_ACR_SERVER }}/indian-constitution-chatbot:latest
          docker push ${{ secrets.AZURE_ACR_SERVER }}/ndian-constitution-chatbot:latest

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ndian-constitution-chatbot'
          images: '${{ secrets.AZURE_ACR_SERVER }}/ndian-constitution-chatbot:latest'
