name: Deploy to Azure WebApp

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev  # Use the 'dev' environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry (ACR)
        run: echo ${{ secrets.AZURE_ACR_PASSWORD }} | docker login ${{ secrets.AZURE_ACR_SERVER }} -u ${{ secrets.AZURE_ACR_USERNAME }} --password-stdin
      
      - name: Build and push Docker image
        run: |
          docker build . -t ${{ secrets.AZURE_ACR_SERVER }}/indian-constitution:latest
          docker push ${{ secrets.AZURE_ACR_SERVER }}/indian-constitution:latest

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'indian-constitution'
          images: '${{ secrets.AZURE_ACR_SERVER }}/indian-constitution:latest'

      - name: Set environment variables for Azure WebApp
        run: |
          az webapp config appsettings set --name 'indian-constitution' --resource-group 'rg-cm-ai-apps' --settings AZURE_OPENAI_ENDPOINT=${{ secrets.AZURE_OPENAI_ENDPOINT }} AZURE_OPENAI_API_KEY=${{ secrets.AZURE_OPENAI_API_KEY }} AZURE_OPENAI_ASSISTANT_ID=${{ secrets.AZURE_OPENAI_ASSISTANT_ID }}
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}