[theme]
primaryColor="#0A2081"  # A dark, elegant blue-gray for a modern professional look
backgroundColor="#FFFFFF"  # Crisp white for a clean, minimal background
secondaryBackgroundColor="#FAF9F6"  # A soft, light gray for sections
textColor="#34495E"  # A dark, easy-to-read blue-gray for modern contrast
font="sans serif"

[logger]
level = "info"